//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invent.assets.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_msg_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_msg_lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Invent.assets.lang.en_msg_lang", typeof(en_msg_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter address..
        /// </summary>
        public static string AddressReq {
            get {
                return ResourceManager.GetString("AddressReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select city..
        /// </summary>
        public static string CityReq {
            get {
                return ResourceManager.GetString("CityReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter company name..
        /// </summary>
        public static string CompanyNameReq {
            get {
                return ResourceManager.GetString("CompanyNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter confirm password..
        /// </summary>
        public static string ConfirmPassReq {
            get {
                return ResourceManager.GetString("ConfirmPassReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select country..
        /// </summary>
        public static string CountryReq {
            get {
                return ResourceManager.GetString("CountryReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter display name..
        /// </summary>
        public static string DisplayNameReq {
            get {
                return ResourceManager.GetString("DisplayNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email address..
        /// </summary>
        public static string EmailReq {
            get {
                return ResourceManager.GetString("EmailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter first name..
        /// </summary>
        public static string FirstNameReq {
            get {
                return ResourceManager.GetString("FirstNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter PAN number..
        /// </summary>
        public static string PANReq {
            get {
                return ResourceManager.GetString("PANReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password..
        /// </summary>
        public static string PasswordReq {
            get {
                return ResourceManager.GetString("PasswordReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter phone number..
        /// </summary>
        public static string PhoneReq {
            get {
                return ResourceManager.GetString("PhoneReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter pincode..
        /// </summary>
        public static string PinCode {
            get {
                return ResourceManager.GetString("PinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select state..
        /// </summary>
        public static string StateReq {
            get {
                return ResourceManager.GetString("StateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter TIN number..
        /// </summary>
        public static string TINReq {
            get {
                return ResourceManager.GetString("TINReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email address..
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
    }
}
